name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      APP_DB_USERNAME: ${{ secrets.POSTGRES_USER }}
      APP_DB_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      APP_DB_NAME: ${{ secrets.POSTGRES_DB }}
    services:
      postgres:
        image: postgres:14.3
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Init modules
      run: go mod init github.com/EKranjec/ContinuousDeliveryInAgileSoftwareDevelopment
    - name: Get dependencies
      run: |
        go get github.com/gorilla/mux
        go get github.com/lib/pq
    - name: Build
      run: go build -v
    - name: Test
      run: go test -v
